---
title: "SNAP Participation"
author: "Marissa Cook"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import and filter data}
library(readxl)
library(dplyr)

data <- read_excel(path = "../Data/FoodAccessResearchAtlasData2019.xlsx",
                   sheet = "Food Access Research Atlas")

dictionary <- read_excel(path = "../Data/FoodAccessResearchAtlasData2019.xlsx",
                    sheet = "Variable Lookup")

str(data) #some numeric cols are classified as 'chr'

columns_of_interest <- c("State","CensusTract", "POP2010","OHU2010",
                         "PovertyRate", "MedianFamilyIncome", "LAPOP1_10",
                         "LAPOP05_10", "LAPOP1_20", "LALOWI1_10",
                         "LALOWI05_10", "LALOWI1_20", "laseniorshalf",
                         "lahunvhalf", "lapop1", "lahunv20",
                         "TractLOWI", "TractHUNV", "TractSNAP")

data_dictionary <- filter(dictionary,dictionary$Field %in% columns_of_interest)

columns_of_interest[3] <- "Pop2010" #name is inconsistent across sheets
data <- data[columns_of_interest] #filter to only select cols
data <- filter(data, State == "Texas")

data[3:19] <- lapply(data[3:19], as.numeric)
str(data)

```


```{r data exploration}
dim(data)
cat("The number of states:", length(unique(data$State)),unique(data$State))
cat("The number of census tracks:", length(unique(data$CensusTract)))

library(reshape2)
long_data <- reshape2::melt(data, id.vars= c("State", "CensusTract"))

library(ggplot2)
histograms <- ggplot(long_data, aes(x=value))+
                    geom_histogram()+
                    facet_wrap(~variable, scales = "free")
histograms

boxplots <- ggplot(long_data, aes(x=value))+
                    geom_boxplot()+
                    facet_wrap(~variable, scales = "free")
boxplots

```


```{r data transformation}

# Calculate percentage of missing values per column
missingPCT = sapply(data, function(x) {sum(is.na(x)) / length(x)}) * 100
missingPCT <- round(missingPCT, 3)
missingPCT
#ALERT: lahunv20  HAS HIGH MISSINGNESS: 97% SO DROP THIS COLUMN

data <- data %>% select(-lahunv20)

#imputation: median
median_value <- NULL
#median imputation because there are outliers
for (i in 3:18){
  if (is.numeric(data[[i]])){
    median_value <- median(data[[i]], na.rm = TRUE)
    data[is.na(data[[i]]),i] <- median_value
  } 
}

predictors <- paste(names(data[3:18] %>% select(-TractSNAP)), collapse = " + ") 
formula <- as.formula(paste("TractSNAP ~", predictors))
library(performance)
vif_results <- check_collinearity(lm(formula, data = data[3:18]))
vif_results$VIF <- format(vif_results$VIF, scientific = F) 
vif_results$VIF <- as.numeric(vif_results$VIF) 

#drop variables that have a VIF >= 10
single_predictors <- filter(vif_results, VIF < 10)

final_data <- data[single_predictors$Term]
final_data$State <- data$State
final_data$CensusTract <- data$CensusTract
final_data$TractSNAP <- data$TractSNAP

```


```{r model exploration}

predictors <- paste(names(final_data[1:8]), collapse = " + ") 
formula <- as.formula(paste("TractSNAP ~", predictors))

model <- lm(formula, data = final_data)
model
summary(model)


#check model assumptions
plot(model)
confint(model)

```






